### ISSUE TITLE
プレイヤーが宿屋のNPCにぶつかるとガクガク震える

### ISSUE THREAD

**Issue by ryosangataRYOSAN** [haruyan721/Original_RPG#5]
### UpdateとFixedUpdateの違いってなんだったでしょうか？
- この答えが解決へのヒント！

**Comment by haruyan721** [comment]
直りました！ありがとうございます!違いはその関数が呼ばれる回数の違いですよね？

**Comment by ryosangataRYOSAN** [comment]
惜しい！確かに呼ばれる回数は違うけどその回数が違う理由が大事
FixedUpdateがどんなタイミングで呼ばれるか調べてみよう

**Comment by haruyan721** [comment]
えーっと・・Updateは毎フレーム呼び出されるから、PCの処理能力によって呼び出される回数が不規則になる。FixedUpdateはunity上で呼び出される間隔が決まっているから呼び出される回数が決まっている。でしたっけ？

**Comment by ryosangataRYOSAN** [comment]
ほぼ正解
重要なのはFixedUpdateが呼び出させる回数が決まっている理由
FixedUpdateの呼び出しは物理演算（当たり判定とか）の処理をした時だから今回みたいに物理演算が絡む処理（transformの値を変えるとか）はFixedUpdateの方が良いんだ！

**Comment by haruyan721** [comment]
わかりました！ありがとうございます！
